language: bash

services: docker

env:
  - VARIANT=php-7.2
  - VARIANT=php-7.3
  
before_script:
  - scripts/prepare-build
  - cd "$VARIANT"
  - image="richardregeer/web-development:${VARIANT}"

script:
  - if [ "$VARIANT" == "php-7.2" ]; then docker build -t "richardregeer/web-development:php" .; fi
  - docker build -t "$image" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$image"

after_script:
- docker images
